import Head from 'next/head'


export default function Deadpage() {
    return (
        <>

            <Head>
                <title>Dead Page - George cosmetics</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className=''>
                <div>
                    <ol>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead page </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead page </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead page </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead page </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead page </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead page </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead page </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead page </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead page </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead page </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead page </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead page </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead page </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead page </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead page </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead page </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead page </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead page </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead page </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead page </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead page </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead page </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead page </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead page </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead page </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead page </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead page </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead page </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead page </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead page </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead page </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead page </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead page </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagev </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagev </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagev </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagev </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagev </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagev </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagev </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagev </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagev </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagev </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagev </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagev </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagev </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagev </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagev </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagev </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagev </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagev </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagev </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagev </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagev </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagev </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagev </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagev </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagev </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagev </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagev </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagev </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagev </li>
                        <li>dead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagedead pagev </li>
                    </ol>
                </div>
            </main>
        </>
    )
}
