import Head from 'next/head';

import { sanity_client } from '../library/sanity-client';
import HeroBanner from '../components/landingPage/HeroBanner';


interface IProps {
    bannerData: string;
}

export default function Home({ bannerData }: IProps) {

  

    return (
        <>

            <Head>
                <title>Home - George cosmetics</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <main className=''>
                landing page
                {/* <HeroBanner heroBanner={bannerData.length && bannerData[0]} /> */}
                <h2>Banner</h2>
                <h2>Products</h2>
            </main>
        </>
    )
}


export const getServerSideProps = async () => {
    const bannerQuery = '*[_type == banner]';
    const bannerData = await sanity_client.fetch(bannerQuery);


    return {
        props: { bannerData }
    }
}