import Head from 'next/head'

export default function Home() {


    return (
        <>

            <Head>
                <title>Home - George cosmetics</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <main className=''>
                landing page
                {/* <img src={urlFor(heroBanner.image)} */}

                <h2>Banner</h2>
                <h2>Products</h2>
            </main>
        </>
    )
}
