// interface
import IPageProps from "../interfaces/page";

// next
import React, { useState, useContext } from "react";
import Head from 'next/head';
import Link from "next/link";

// stlyes
import styles from '../styles/pages/signin.module.scss';

// auth
import { UserAuth } from '../context/AuthContext';

// errors
import { signinError } from "../components/errorMsg/signinError";

const RegisterPage: IPageProps = () => {

    const [email, setEmail] = useState<string>('');
    const [password, setPassword] = useState<string>('');
    const [confirm, setConfirm] = useState<string>('');
    const [error, setError] = useState<string>('');
    const [registering, setRegistering] = useState<boolean>(false);

    const { createUser } = UserAuth();

    const handleSubmit = async (e: any) => {
        e.preventDefault();
        setError('');




        try {
            await createUser(email, password);
            setError('');
        } catch (e) {
            setError(e.message);
            console.log(e.message);
            console.log(error);
        }
    }

    return (

        <>
            <Head>
                <title>Register - George cosmetics</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className=''>
                <div className={styles.container}>
                    <h2>Register</h2>
                    <div className={styles.wrapper}>
                        <form onSubmit={handleSubmit}>
                            <input
                                type='email'
                                name='email'
                                id='email'
                                placeholder='Enter Email'
                                value={email}
                                onChange={(event) => setEmail(event.target.value)}
                            />
                            {
                                <signinError props={error} />
                            }

                            <input
                                autoComplete="new-password"
                                type='password'
                                name='password'
                                id='password'
                                placeholder='Enter Password'
                                value={password}
                                onChange={(event) => setPassword(event.target.value)}
                            />
                            <input
                                autoComplete="new-password"
                                type='password'
                                name='confirm'
                                id='confirm'
                                placeholder='Confrim Password'
                                value={confirm}
                                onChange={(event) => setConfirm(event.target.value)}
                            />


                            <button
                            // disabled={!registering}
                            >
                                Sign In
                            </button>
                        </form>
                    </div>
                </div>
            </main>
        </>

    )
}

export default RegisterPage;