import { useState } from "react";
import { getAuth, createUserWithEmailAndPassword } from "firebase/auth";
import styles from '../styles/pages/signin.module.scss';

import Head from 'next/head';

import auth from '../firebase';

import Link from "next/link";


export default function register() {

    const [registering, setRegistering] = useState<boolean>(false);
    const [email, setEmail] = useState<string>('');
    const [password, setPassword] = useState<string>('');
    const [confirmPassword, setConfirmPassword] = useState<string>('');
    const [error, setError] = useState<string>('');


    const signUpWithEmailAddressAndPassword = () => {

        if (password !== confirmPassword) {
            setError("passwords don't match")
        }


        if (error !== '') {
            setError('');
        }

        setRegistering(true);

        createUserWithEmailAndPassword(auth, email, password)
            .then((userCredential) => {
                // Signed in
                const user = userCredential.user;
                console.log(userCredential);
            })
            .catch((error) => {
                const errorCode = error.code;
                const errorMessage = error.message;

                console.log(errorCode);
                console.log(errorMessage);

                setRegistering(false);
            })
    }

    return (
        <>

            <Head>
                <title>Register - George cosmetics</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className=''>
                <div className={styles.container}>
                    <h2>Register</h2>
                    <div className={styles.wrapper}>
                        <form>
                            <label>E-mail</label>
                            <input type="email" placeholder='Email'
                                value={email}
                                onChange={event => setEmail(event.target.value)}
                            />

                            <label>Password</label>
                            <input type="password" placeholder='Password'
                                value={password}
                                onChange={event => setPassword(event.target.value)}
                            />

                            <label>Repeat Password</label>
                            <input type="password" placeholder='Repeat Password'
                                value={confirmPassword}
                                onChange={event => setConfirmPassword(event.target.value)}
                            />

                        </form>
                        <button type='submit'
                            onClick={() => signUpWithEmailAddressAndPassword()}
                        >Submit</button>
                    </div>
                    <Link href="/signin">
                        <p>Already have an account?</p>
                    </Link>
                </div>
            </main>
        </>
    )
}
