// next
import Head from 'next/head'
import Link from 'next/link';
import { useRouter } from "next/router";
import { useState } from 'react';

// styles
import styles from '../styles/pages/signin.module.scss';

// auth
import { UserAuth } from '../context/AuthContext';



export default function Home() {

    const [email, setEmail] = useState('')
    const [password, setPassword] = useState('')
    const [error, setError] = useState('')

    const { signInUser } = UserAuth();

    const router = useRouter();

    const handleSubmit = async (event: any) => {
        event.preventDefault();
        setError('');

        try {
            await signInUser(email, password);
            setError('');
            router.push('/');

        } catch (err) {
            console.log(err.message);
            setError(err.message);
            console.log(error);
        }
    };

    return (
        <>

            <Head>
                <title>SignIn - George cosmetics</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className=''>
                <div className={styles.container}>
                    <h2>Sign In</h2>
                    <div className={styles.wrapper}>
                        <form
                            onSubmit={handleSubmit}
                        >
                            <label>E-mail</label>
                            <input
                                type='email'
                                name='email'
                                id='email'
                                placeholder='Enter Email'
                                value={email}
                                onChange={(event) => setEmail(event.target.value)}
                            />
                            <label>Password</label>
                            <input
                                type='password'
                                name='password'
                                id='password'
                                placeholder='Enter Password'
                                value={password}
                                onChange={(event) => setPassword(event.target.value)}
                            />
                            <button type='submit'>Submit</button>
                        </form>
                    </div>
                    <Link href="/register">
                        <p>Don't have an account?</p>
                    </Link>
                </div>
            </main>
        </>
    )
}
